routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', '\App\Http\Controllers\PagesController@index');
Route::get('/about', '\App\Http\Controllers\PagesController@about');
Route::get('/contact', '\App\Http\Controllers\PagesController@contact');
Route::get('/posts', '\App\Http\Controllers\PagesController@posts');
Route::get('/posts/{slug}', '\App\Http\Controllers\PagesController@post');
Route::get('/stories', '\App\Http\Controllers\PagesController@stories');
Route::post('/comments/{post_id}', '\App\Http\Controllers\PagesController@comment')->name('addComments');
Route::post('/stories/send', '\App\Http\Controllers\PagesController@store')->name('pages.store');
Route::post('/submissions', '\App\Http\Controllers\PagesController@submit')->name('submissions.post');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::middleware(['auth'])->prefix('dashboard')->group(function () {
    Route::resource('/socials', '\App\Http\Controllers\SocialsController');
    Route::resource('/categories', '\App\Http\Controllers\CategoriesController');
    Route::resource('/authors', '\App\Http\Controllers\AuthorsController');
    Route::resource('/stories', '\App\Http\Controllers\StoriesController');
    Route::resource('/slides', '\App\Http\Controllers\SlidesController');
    Route::resource('/posts', '\App\Http\Controllers\PostsController');
    Route::resource('/comments', '\App\Http\Controllers\CommentsController');
    Route::resource('/submissions', '\App\Http\Controllers\SubmissionsController');
    Route::get('/posts/deleteImage/{id}', '\App\Http\Controllers\PostsController@deleteImage');
});

require __DIR__.'/auth.php';

app/Models/Story.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Story extends Model
{
    use HasFactory;
}

app/Http/Controllers/StoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Story;
use Illuminate\Support\Str;
use Image;

class StoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stories =  Story::all();
        return view('dashboard.stories.index')->with("stories",$stories);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $story = Story::find($id);
        return view('dashboard.stories.edit')->with('story', $story);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'story' => 'required',
            'email' => 'required',
            'image' => 'max:5120|image',
        ]);

        $story = Story::find($id);
        $story->name = $request->input('name');
        $story->email = $request->input('email');
        $story->story = $request->input('story');
        $story->confirmed = $request->input('confirmed');
        if($request->hasFile('image')){
            $filenameWithExt = $request->file('image')->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $extension = $request->file('image')->getClientOriginalExtension();
            $filename = Str::slug($filename, '-');
            $fileNameToStore = $filename.'_'.time().'.'.$extension;

            $image_original = Image::make($request->file('image')->getRealPath());
            $image_original->backup();
            $image_original->save(public_path('images/stories/'.$fileNameToStore));

            $story->image = $fileNameToStore;
        }
        $story->save();

        return redirect('/dashboard/stories/')->with('success', 'Story updated!');
    }


    public function destroy($id)
    {
        $story = Story::find($id);
        $story->delete();
        return redirect('/dashboard/stories/')->with('success', 'Story Removed!');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard/stories/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    Add Story
                </h2>
            </div>
            <div class="col-md-4">
                <a href="{{ route('stories.index') }}" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-green-400 hover:bg-green-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 float-right">
                    Stories
                </a>
            </div>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                {!! Form::open(['route' => 'stories.store', 'method' => 'POST', 'enctype' => 'multipart/form-data']) !!}
                    <div class="shadow overflow-hidden sm:rounded-md">
                        <div class="px-4 py-5 bg-white sm:p-6">
                            <div class="grid grid-cols-6 gap-6">
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="title" class="block font-medium text-gray-700">Title</label>
                                    <input type="text" name="title" id="title" autocomplete="title" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" required>
                                </div>

                                <div class="col-span-12 sm:col-span-12">
                                    <label for="image" class="block font-medium text-gray-700">Image</label>
                                    <input type="file" name="image" id="image" autocomplete="icon" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" required>
                                </div>

                                <div class="col-span-12 sm:col-span-12">
                                    <label for="content" class="block font-medium text-gray-700">Content</label>
                                    <textarea name="content" id="content" cols="30" rows="10" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" required></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                Create
                            </button>
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/dashboard/stories/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    Edit Story
                </h2>
            </div>
            <div class="col-md-4">
                <a href="{{ route('stories.index') }}" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-green-400 hover:bg-green-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 float-right">
                    Stories
                </a>
            </div>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                {!! Form::open(['route' => ['stories.update',$story->id], 'method' => 'POST','enctype'=>'multipart/form-data']) !!}
                <div class="shadow overflow-hidden sm:rounded-md">
                    <div class="px-4 py-5 bg-white sm:p-6">
                        <div class="grid grid-cols-6 gap-6">
                            <div class="col-span-12 sm:col-span-12">
                                <label for="name" class="block font-medium text-gray-700">Name</label>
                                <input type="text" name="name" value="{{$story->name}}" id="name" autocomplete="title" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" required>
                            </div>

                            <div class="col-span-12 sm:col-span-12">
                                <label for="email" class="block font-medium text-gray-700">Email</label>
                                <input type="email" name="email" value="{{$story->email}}" id="title" autocomplete="title" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" required>
                            </div>

                            <div class="col-span-12 sm:col-span-12">
                                <label for="confirmed" class="block font-medium text-gray-700">Confirmed</label>
                                <select name="confirmed" id="confirmed" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">
                                    <option value="1" @if($story->confirmed == 1) selected @endif>Confirmed</option>
                                    <option value="0" @if($story->confirmed == 0) selected @endif>Not Confirmed</option>
                                </select>
                            </div>

                            <div class="col-span-12 sm:col-span-12">
                                <label for="image" class="block font-medium text-gray-700">Image</label>
                                @if(!empty($story->image))
                                    <a href="/images/stories/{{$story->image}}" target="_blank">
                                        <img src="/images/stories/{{$story->image}}" alt="{{$story->title}}" width="200" class="mt-1">
                                    </a>
                                @endif
                                <input type="file" name="image" id="image" autocomplete="icon" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">
                            </div>

                            <div class="col-span-12 sm:col-span-12">
                                <label for="story" class="block font-medium text-gray-700">Content</label>
                                <textarea name="story" id="story" cols="30" rows="10" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" required>{{$story->story}}</textarea>
                            </div>
                        </div>
                    </div>
                    {{Form::hidden('_method','PUT')}}
                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                        <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                            Save
                        </button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/dashboard/stories/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    Stories
                </h2>
            </div>
            <div class="col-md-4">
                <a href="{{ route('stories.create') }}" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-green-400 hover:bg-green-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 float-right">
                    Add Story
                </a>
            </div>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="bg-white pb-4 px-4 rounded-md w-full">
                    <div class="overflow-x-auto mt-6">

                        <table class="table-auto border-collapse w-full">
                            <thead>
                            <tr class="bg-gray-200 rounded-lg text-sm font-medium text-gray-700 text-left" style="font-size: 0.9674rem">
                                <th class="px-4 py-2">Title</th>
                                <th class="px-4 py-2">Confirmed</th>
                                <th class="px-4 py-2">Operations</th>
                            </tr>
                            </thead>
                            <tbody class="text-sm font-normal text-gray-700">
                            @foreach($stories as $story)
                                <tr class="hover:bg-gray-100 border-b border-gray-200 py-10">
                                    <td class="px-4 py-4">{{$story->name}}</td>
                                    <td class="px-4 py-4">
                                        @if($story->confirmed == 1)
                                            <span class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-green-400 hover:bg-green-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Confirmed</span>
                                        @else
                                            <span class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Not Confirmed</span>
                                        @endif
                                    </td>
                                    <td class="px-4 py-4">
                                        <div class="flex flex-wrap">
                                            <a href="/dashboard/stories/{{$story->id}}/edit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-yellow-400 hover:bg-yellow-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mr-2">
                                                Edit
                                            </a>
                                            {!! Form::open(['route' => ['stories.destroy', $story->id], 'method' => 'POST', 'class' => 'inline-block']) !!}
                                            {{Form::hidden('_method', 'DELETE')}}
                                            <button onclick="return confirm('Are you sure?')" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                                Delete
                                            </button>
                                            {!! Form::close() !!}
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>