routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', '\App\Http\Controllers\PagesController@index');
Route::get('/about', '\App\Http\Controllers\PagesController@about');
Route::get('/contact', '\App\Http\Controllers\PagesController@contact');
Route::get('/posts', '\App\Http\Controllers\PagesController@posts');
Route::get('/posts/{slug}', '\App\Http\Controllers\PagesController@post');
Route::get('/stories', '\App\Http\Controllers\PagesController@stories');
Route::post('/comments/{post_id}', '\App\Http\Controllers\PagesController@comment')->name('addComments');
Route::post('/stories/send', '\App\Http\Controllers\PagesController@store')->name('pages.store');
Route::post('/submissions', '\App\Http\Controllers\PagesController@submit')->name('submissions.post');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::middleware(['auth'])->prefix('dashboard')->group(function () {
    Route::resource('/socials', '\App\Http\Controllers\SocialsController');
    Route::resource('/categories', '\App\Http\Controllers\CategoriesController');
    Route::resource('/authors', '\App\Http\Controllers\AuthorsController');
    Route::resource('/stories', '\App\Http\Controllers\StoriesController');
    Route::resource('/slides', '\App\Http\Controllers\SlidesController');
    Route::resource('/posts', '\App\Http\Controllers\PostsController');
    Route::resource('/comments', '\App\Http\Controllers\CommentsController');
    Route::resource('/submissions', '\App\Http\Controllers\SubmissionsController');
    Route::get('/posts/deleteImage/{id}', '\App\Http\Controllers\PostsController@deleteImage');
});

require __DIR__.'/auth.php';

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        <link rel="stylesheet" href="{{ asset('css/grid.min.css') }}">

        <!-- Scripts -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
        <script src="/ckeditor/ckeditor.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
        <script type="text/javascript">
            $(document).ready(function() {

                $('.textarea').each(function(e){
                    CKEDITOR.replace(this.id, {
                        height: 300,
                        filebrowserBrowseUrl: "{{asset('/dashboard/file_browser')}}"
                    });
                });

            });
            @if(count($errors) > 0)
            @foreach($errors->all() as $error)
            Swal.fire({
                title: 'Error!',
                text: '{{$error}}',
                icon: 'error',
                toast: true,
                position: 'top-end',
                timerProgressBar: true,
                timer: 2000,
                showConfirmButton: false
            });
            @endforeach
            @endif

            @if(session('success'))
            Swal.fire({
                title: 'Success!',
                text: '{{session('success')}}',
                icon: 'success',
                toast: true,
                position: 'top-end',
                timerProgressBar: true,
                timer: 2000,
                showConfirmButton: false
            })
            @endif

            @if(session('error'))
            Swal.fire({
                title: 'Error!',
                text: '{{session('error')}}',
                icon: 'error',
                toast: true,
                position: 'top-end',
                timerProgressBar: true,
                timer: 2000,
                showConfirmButton: false
            })
            @endif
        </script>
    </body>
</html>

resources/views/layouts/core.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="FusionBlog - Personal Blog Theme">
    <meta name="keywords" content="Html, Css, jQuery, JavaScript, FusionBlog, blog, personal blog, template, news theme">

    <!-- Title -->
    <title>FusionBlog - Personal Blog Theme</title>
    <!-- Favicon -->
    <link rel="icon" href="https://via.placeholder.com/80x80">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700;900&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap">

    <!-- Font Awesome Css -->
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <!-- Bootstrap Css -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <!-- Slick Css -->
    <link rel="stylesheet" href="/css/slick.min.css">
    <!-- Main Style Css -->
    <link rel="stylesheet" href="/css/main.css">

    <!--[if lt IE 9]>
    <script src="/js/html5shiv.min.js"></script>
    <script src="/js/respond.min.js"></script>
    <![endif]-->

    <script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=625f1f5e7c21c20019e99d80&product=sop' async='async'></script>
</head>
<body>

<!-- ========== Start Loading ========== -->

<div class="loading">
    <div class="loading-content">
        <div class="inner-item"></div>
        <div class="inner-item"></div>
        <div class="inner-item"></div>
        <div class="inner-item"></div>
        <div class="inner-item"></div>
    </div>
</div>

<!-- ========== End Loading ========== -->

<!-- ========== Start Header ========== -->

<header>
    <div class="site-brand text-center">
        <div class="container">
            <a href="index.html">
                <h2>SRI Repository</h2>
            </a>
            <p class="site-description">Security Requirement Identification</p>
        </div>
    </div>
    <div class="header-inner">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-8 col-xs-3 pos-s">
                    <button class="menu-toggle">
                        <span class="bar"></span>
                        <span class="bar"></span>
                        <span class="bar"></span>
                    </button>
                    <nav class="navbar navbar-default">
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav">
                                <li class="menu-item active">
                                    <a href="/">Home</a>
                                </li>
                                <li class="menu-item"><a href="/about">About</a></li>
                                <li class="menu-item"><a href="/contact">Contact</a></li>
                                <li class="menu-item"><a href="/faq">FAQ</a></li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <div class="col-md-3 col-sm-4 col-xs-9 text-md-center">
                    <div class="search-toggle">
                        <i class="fa fa-search"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="search-area">
				<span class="close-search">
                    <i class="fa fa-close"></i>
				</span>
        <div class="display-table">
            <div class="display-table-cell">
                <form role="search" method="get" class="search-form" action="#">
                    <input type="search" class="search-field" placeholder="Search..." name="s" required="required" />
                    <button type="submit" class="search-submit"><i class="fa fa-search"></i></button>
                </form>
            </div>
        </div>
    </div>
</header>

<!-- ========== End Header ========== -->

@yield('content')

<!-- ========== Start Scroll To Top ========== -->

<a href="#" class="scroll-top">
    <span><i class="fa fa-arrow-up"></i></span>
</a>

<!-- ========== End Scroll To Top ========== -->

<!-- ========== Start Footer ========== -->

<div class="footer text-center">
    <div class="footer-info">
        <div class="container">
            <p class="copyright">
                copyright &copy; 2020 FusionBlog, All Right Reserved
            </p>
            <div class="textwidget custom-html-widget">
                <ul class="social-icons-menu list-unstyled">
                    <li><a href="#" target="_blank"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" target="_blank"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="#" target="_blank"><i class="fa fa-pinterest"></i></a></li>
                    <li><a href="#" target="_blank"><i class="fa fa-youtube"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- ========== End Footer ========== -->

<!-- ========== Js ========== -->

<!-- jQuery -->
<script src="/js/jquery-3.2.1.min.js"></script>
<!-- Bootstrap Js -->
<script src="/js/bootstrap.min.js"></script>
<!-- Slick Js -->
<script src="/js/slick.min.js"></script>
<!-- Main Js -->
<script src="/js/main.js"></script>
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                    <x-nav-link :href="route('posts.index')" :active="request()->routeIs('posts.index')">
                        {{ __('Posts') }}
                    </x-nav-link>
                    <x-nav-link :href="route('categories.index')" :active="request()->routeIs('categories.index')">
                        {{ __('Categories') }}
                    </x-nav-link>
                    <x-nav-link :href="route('authors.index')" :active="request()->routeIs('authors.index')">
                        {{ __('Authors') }}
                    </x-nav-link>
                    <x-nav-link :href="route('comments.index')" :active="request()->routeIs('comments.index')">
                        {{ __('Comments') }}
                    </x-nav-link>
                    <x-nav-link :href="route('submissions.index')" :active="request()->routeIs('submissions.index')">
                        {{ __('Submissions') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>